## Filtering & Sorting

In [1]:
## Import Libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
euro_2012_data = pd.read_csv('Euro_2012_stats_TEAM.csv')
euro_2012_data.head(10)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17

In [4]:
euro_2012_data.shape

(16, 35)

In [5]:
euro_2012_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     object
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     object
 5   % Goals-to-shots            16 non-null     object
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     object
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     object
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), object(5)
memory usage: 4.5+ KB

In [6]:
# How many teams participated in euro_worldcup_2012

In [7]:
euro_2012_data.Team.value_counts

<bound method IndexOpsMixin.value_counts of 0                 Croatia
1          Czech Republic
2                 Denmark
3                 England
4                  France
5                 Germany
6                  Greece
7                   Italy
8             Netherlands
9                  Poland
10               Portugal
11    Republic of Ireland
12                 Russia
13                  Spain
14                 Sweden
15                Ukraine
Name: Team, dtype: object>

In [8]:
euro_2012_data.Team.nunique()

16

In [9]:
euro_2012_data.Team.unique()

array(['Croatia', 'Czech Republic', 'Denmark', 'England', 'France',
       'Germany', 'Greece', 'Italy', 'Netherlands', 'Poland', 'Portugal',
       'Republic of Ireland', 'Russia', 'Spain', 'Sweden', 'Ukraine'],
      dtype=object)

In [10]:
# View dataset with Teams,Yellow and Red cards

In [11]:
team_red_yellow_card = euro_2012_data[['Team','Yellow Cards','Red Cards']]
team_red_yellow_card

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [12]:
# Sort the team by red card

In [13]:
team_red_yellow_card.sort_values(by = 'Red Cards', ascending = False)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
7                 Italy            16          0
8           Netherlands             5          0
10             Portugal            12          0
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [14]:
# On an average , a team is getting how many yellow cards

In [15]:
team_red_yellow_card['Yellow Cards'].mean()

7.4375

In [16]:
round(team_red_yellow_card['Yellow Cards'].mean())

7

In [17]:
# Filter the team who scored more than 8 goals

In [18]:
euro_2012_data[euro_2012_data.Goals>8]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

In [20]:
# Get the team names starting with letter 's'

In [22]:
euro_2012_data[euro_2012_data.Team.str.startswith('S')]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18

In [23]:
# Get the first 7 records of first 5 columns

In [24]:
euro_2012_data.head(7)

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20

In [25]:
## Index Locater

In [29]:
euro_2012_data.iloc[0:8 , 0:6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots
0,Croatia,4,13,12,51.9%,16.0%
1,Czech Republic,4,13,18,41.9%,12.9%
2,Denmark,4,10,10,50.0%,20.0%
3,England,5,11,18,50.0%,17.2%
4,France,3,22,24,37.9%,6.5%
5,Germany,10,32,32,47.8%,15.6%
6,Greece,5,8,18,30.7%,19.2%
7,Italy,6,34,45,43.0%,7.5%

In [30]:
#enumerate - will return 2 values - column index and your column name
for index_no,column_name in enumerate(euro_2012_data):
    print(index_no, column_name)

0 Team
1 Goals
2 Shots on target
3 Shots off target
4 Shooting Accuracy
5 % Goals-to-shots
6 Total shots (inc. Blocked)
7 Hit Woodwork
8 Penalty goals
9 Penalties not scored
10 Headed goals
11 Passes
12 Passes completed
13 Passing Accuracy
14 Touches
15 Crosses
16 Dribbles
17 Corners Taken
18 Tackles
19 Clearances
20 Interceptions
21 Clearances off line
22 Clean Sheets
23 Blocks
24 Goals conceded
25 Saves made
26 Saves-to-shots ratio
27 Fouls Won
28 Fouls Conceded
29 Offsides
30 Yellow Cards
31 Red Cards
32 Subs on
33 Subs off
34 Players Used

In [32]:
df = euro_2012_data[['Yellow Cards','Red Cards','Shooting Accuracy']]

In [33]:
df

    Yellow Cards  Red Cards Shooting Accuracy
0              9          0             51.9%
1              7          0             41.9%
2              4          0             50.0%
3              5          0             50.0%
4              6          0             37.9%
5              4          0             47.8%
6              9          1             30.7%
7             16          0             43.0%
8              5          0             25.0%
9              7          1             39.4%
10            12          0             34.3%
11             6          1             36.8%
12             6          0             22.5%
13            11          0             55.9%
14             7          0             47.2%
15             5          0             21.2%

In [34]:
euro_2012_data.iloc[:,30:32]

    Yellow Cards  Red Cards
0              9          0
1              7          0
2              4          0
3              5          0
4              6          0
5              4          0
6              9          1
7             16          0
8              5          0
9              7          1
10            12          0
11             6          1
12             6          0
13            11          0
14             7          0
15             5          0

In [35]:
#loc 
euro_2012_data.loc[:7,'Yellow Cards':'Red Cards']

   Yellow Cards  Red Cards
0             9          0
1             7          0
2             4          0
3             5          0
4             6          0
5             4          0
6             9          1
7            16          0

In [36]:
# Display the Shooting Accuracy of Denmark ,France and Greece

In [37]:
## filtering using set_index

In [38]:
euro_2012_data.set_index('Team' , inplace = True)

In [39]:
euro_2012_data

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,13,81.3%,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,10,66.7%,25,38,8,4,0,7,7,15
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,22,88.1%,43,45,6,5,0,11,11,16
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17
Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,...,13,65.1%,67,48,12,9,1,12,12,20
Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,...,20,74.1%,101,89,16,16,0,18,18,19
Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,...,6,66.7%,48,56,3,7,1,7,7,17
Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,...,10,71.5%,73,90,10,12,0,14,14,16
Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,...,17,65.4%,43,51,11,6,1,10,10,17
Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,...,10,77.0%,34,43,4,6,0,7,7,16
Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,...,15,93.8%,102,83,19,11,0,17,17,18
Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,...,8,61.6%,35,51,7,7,0,9,9,18
Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,...,13,76.5%,48,31,4,5,0,9,9,18

In [41]:
euro_2012_data.loc[['Denmark','France','France'],['Shooting Accuracy']]

        Shooting Accuracy
Team
Denmark             50.0%
France              37.9%
France              37.9%